### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by tanghailan** [zykzhangyukang/admin#1]
你好，我把base-parent安装到我maven本地，我的admin好像识别不到maven坐标一样

**Comment by zykzhangyukang** [comment]
检查一下本地厂库是否已经有安装好的jar包，如果已经存在，是否有错误提示，截图看看。

**Comment by tanghailan** [comment]
![Snipaste_2024-08-02_10-00-37](https://github.com/user-attachments/assets/3e02a29d-7039-46a5-818e-15e2d0f28960)
<img width="1609" alt="image" src="https://github.com/user-attachments/assets/c8299d47-3d1b-4c04-b52b-0ab413ac81a7">

**Comment by tanghailan** [comment]
<img width="1252" alt="image" src="https://github.com/user-attachments/assets/eeb8b5d8-0838-433c-8bd1-55c146075df4">
点进去好像都爆红，大佬麻烦看看哈

**Comment by zykzhangyukang** [comment]
![image](https://github.com/user-attachments/assets/f758fba6-a3c3-45fa-8f70-6c23ffc61d23)
![image](https://github.com/user-attachments/assets/2ebd45fc-0297-4335-a543-4e3c4d3c7112)

1. 切换到master拉取最新的代码.
2. maven重新install一下.
3. base-parent使用 1.0.0.RELEASE 版本.

**Comment by zykzhangyukang** [comment]
> <img alt="image" width="1252" src="https://private-user-images.githubusercontent.com/48954604/354436633-eeb8b5d8-0838-433c-8bd1-55c146075df4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NjUyMzUsIm5iZiI6MTcyMjU2NDkzNSwicGF0aCI6Ii80ODk1NDYwNC8zNTQ0MzY2MzMtZWViOGI1ZDgtMDgzOC00MzNjLThiZDEtNTVjMTQ2MDc1ZGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDAyMTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjNhYTcxZWE2Y2FjMjFjZDRjMjkyNDk5NWE5NGFkNTY5OTg5M2UxNjMxNTNhNjhjMTU2MDRmNTZjOTk2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.az7t4Ar-RBZPIGWHBPU-_--r0sf7as414-FLtqDwSrQ"> 点进去好像都爆红，大佬麻烦看看哈

你这个好像还是 1.0.0版本

**Comment by tanghailan** [comment]
好的大佬谢谢了，可以了😊

**Comment by zykzhangyukang** [comment]
好的
